# optional configuration variables that the user can supply

CONFIG_OVERRIDE_SYMBOLS ?= 1
CONFIG_AUTODEDICATE_PML4ES ?= 1
CONFIG_CALLOC_SPECIAL_BUFSIZE ?= 32
CONFIG_REGISTER_PREINIT ?= 1
CONFIG_VIRTMEMALLOC_STATS ?= 1
CONFIG_SYSCALLMETA_HAS_INFO ?= 1

CONFIG_DEBUG_DGLMALLOC ?= 0
CONFIG_DEBUG_VIRTMEM ?= 0
CONFIG_DEBUG_VIRTMEMALLOC ?= 0
CONFIG_DEBUG_VIRTREMAP ?= 0
CONFIG_DEBUG_SYSMALLOC ?= 0
CONFIG_DEBUG_INIT ?= 0
CONFIG_DEBUG_PHYSMEM_ALLOC ?= 0
