#include <unistd.h>
#include <sys/syscall.h>

#include "dangless/common.h"
#include "dangless/syscallmeta.h"

// dangless/build/common/syscallmeta.inc is generated by scripts/generate_syscallmeta.py

static const i8 g_syscall_ptr_params[][SYSCALL_MAX_ARGS + 1] = {
  #define SYSCALL_USERPTR_PARAMS(NUM, NAME, ...) \
    [NUM] = { __VA_ARGS__ },

  #include "dangless/build/common/syscallmeta.inc"
};

const i8 *syscall_get_userptr_params(index_t syscallno) {
  if (syscallno >= ARRAY_LENGTH(g_syscall_ptr_params)
      || g_syscall_ptr_params[syscallno][0] == 0)
    return NULL;

  return g_syscall_ptr_params[syscallno];
}

#if DANGLESS_CONFIG_SYSCALLMETA_HAS_INFO

static const struct syscall_info g_syscall_infos[] = {
  #define SYSCALL_SIGNATURE(NUM, RETTY, NAME, NUM_PARAMS, ...) \
    [NUM] = { \
      NUM, \
      #NAME, \
      #RETTY, \
      NUM_PARAMS, \
      /*params=*/ {

  #define SYSCALL_PARAM(POS, TYPE, NAME, IS_USER_PTR) \
      { POS, #TYPE, #NAME, IS_USER_PTR },

  #define SYSCALL_END(NUM, RETTY, NAME, NUM_PARAMS, ...) \
      } /* end params */, \
      /*signature=*/ #RETTY " " #NAME " (" #__VA_ARGS__ ")" \
    },

  #include "dangless/build/common/syscallmeta.inc"
};

const struct syscall_info *syscall_get_info(index_t syscallno) {
  if (syscallno >= ARRAY_LENGTH(g_syscall_infos)
      || !g_syscall_infos[syscallno].name)
    return NULL;

  return &g_syscall_infos[syscallno];
}

#endif // DANGLESS_CONFIG_SYSCALLMETA_HAS_INFO
