#include <unistd.h>
#include <sys/syscall.h>

#include "dangless/syscallmeta.h"

int g_syscall_ptr_args[][SYSCALL_MAX_NUM_ARGS + 1] = {
  #define SYSCALL_SIGNATURE(RETTYPE, NAME, NUM_PARAMS, ...) /* empty */

  #define SYSCALL_USERPTR_PARAMS(NAME, ...) \
    [__NR_##NAME] = { __VA_ARGS__ },

  // This file is generated by scripts/generate_syscall_metadata.py
  #include "dangless/build/syscallmeta.inc"
};

size_t g_syscall_ptr_args_len = sizeof(g_syscall_ptr_args) / sizeof(g_syscall_ptr_args[0]);
